### ISSUE TITLE
account-vending

### ISSUE THREAD

**Issue by joaorodrig** [awslabs/aws-service-catalog-products#17]
In the Account Vending Machine bootstrapping product, there needs to exist a wait time (e.g. 2mins) to allow for the account creation to complete.

Suggested fix would be to add time.sleep(120) to line 40 for example of the following file:
aws-service-catalog-products/account-vending/account-bootstrap-shared/v1/src/handler.py

**Comment by eamonnfaherty** [comment]
this is now fixed.  we wait until codebuild is available in the newly created account.
