### ISSUE TITLE
Account Vending Bootstrapper - multiple concurrent codebuild executions for long puppet run

### ISSUE THREAD

**Issue by shanesiebken** [awslabs/aws-service-catalog-products#42]
By default, the Bootstrapping lambda function for account-creation is set to retry 2 times after a failed (or uncompleted) CodeBuild pipeline. For a long-running puppet (anything more than 15 minutes), this leads to multiple pipelines being executed concurrently, and can sometimes lead to a failure even when that pipeline (eventually) succeeds.

**Comment by eamonnfaherty** [comment]
this has been resolved.
